package utils;

import static types.Type.ARTWORK;
import static types.Type.DECK_LIST;
import static types.Type.ENERGY;
import static types.Type.EXTRA_RULE;
import static types.Type.PASS_CARD;
import static types.Type.TRAINER;
import com.google.common.collect.ImmutableBiMap;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableSet;
import types.Type;

import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

public class PokemonsData {

    public static ImmutableMap<String, String> POKEMONS_TO_FRENCH = ImmutableMap.<String, String>builder()
            .put("Bulbasaur", "Bulbizarre")
            .put("Ivysaur", "Herbizarre")
            .put("Venusaur", "Florizarre")
            .put("Charmander", "Salamèche")
            .put("Charmeleon", "Reptincel")
            .put("Charizard", "Dracaufeu")
            .put("Squirtle", "Carapuce")
            .put("Wartortle", "Carabaffe")
            .put("Blastoise", "Tortank")
            .put("Caterpie", "Chenipan")
            .put("Metapod", "Chrysacier")
            .put("Butterfree", "Papilusion")
            .put("Weedle", "Aspicot")
            .put("Kakuna", "Coconfort")
            .put("Beedrill", "Dardargnan")
            .put("Pidgey", "Roucool")
            .put("Pidgeotto", "Roucoups")
            .put("Pidgeot", "Roucarnage")
            .put("Rattata", "Rattata")
            .put("Raticate", "Rattatac")
            .put("Spearow", "Piafabec")
            .put("Fearow", "Rapasdepic")
            .put("Ekans", "Abo")
            .put("Arbok", "Arbok")
            .put("Pikachu", "Pikachu")
            .put("Raichu", "Raichu")
            .put("Sandshrew", "Sabelette")
            .put("Sandslash", "Sablaireau")
            .put("Nidoran♀", "Nidoran♀")
            .put("Nidorina", "Nidorina")
            .put("Nidoqueen", "Nidoqueen")
            .put("Nidoran♂", "Nidoran♂")
            .put("Nidorino", "Nidorino")
            .put("Nidoking", "Nidoking")
            .put("Clefairy", "Mélofée")
            .put("Clefable", "Mélodelfe")
            .put("Vulpix", "Goupix")
            .put("Ninetales", "Feunard")
            .put("Jigglypuff", "Rondoudou")
            .put("Wigglytuff", "Grodoudou")
            .put("Zubat", "Nosferapti")
            .put("Golbat", "Nosferalto")
            .put("Oddish", "Mystherbe")
            .put("Gloom", "Ortide")
            .put("Vileplume", "Rafflésia")
            .put("Paras", "Paras")
            .put("Parasect", "Parasect")
            .put("Venonat", "Mimitoss")
            .put("Venomoth", "Aéromite")
            .put("Diglett", "Taupiqueur")
            .put("Dugtrio", "Triopikeur")
            .put("Meowth", "Miaouss")
            .put("Persian", "Persian")
            .put("Psyduck", "Psykokwak")
            .put("Golduck", "Akwakwak")
            .put("Mankey", "Férosinge")
            .put("Primeape", "Colossinge")
            .put("Growlithe", "Caninos")
            .put("Arcanine", "Arcanin")
            .put("Poliwag", "Ptitard")
            .put("Poliwhirl", "Têtarte")
            .put("Poliwrath", "Tartard")
            .put("Abra", "Abra")
            .put("Kadabra", "Kadabra")
            .put("Alakazam", "Alakazam")
            .put("Machop", "Machoc")
            .put("Machoke", "Machopeur")
            .put("Machamp", "Mackogneur")
            .put("Bellsprout", "Chétiflor")
            .put("Weepinbell", "Boustiflor")
            .put("Victreebel", "Empiflor")
            .put("Tentacool", "Tentacool")
            .put("Tentacruel", "Tentacruel")
            .put("Geodude", "Racaillou")
            .put("Graveler", "Gravalanch")
            .put("Golem", "Grolem")
            .put("Ponyta", "Ponyta")
            .put("Rapidash", "Galopa")
            .put("Slowpoke", "Ramoloss")
            .put("Slowbro", "Flagadoss")
            .put("Magnemite", "Magnéti")
            .put("Magneton", "Magnéton")
            .put("Farfetch'd", "Canarticho")
            .put("Doduo", "Doduo")
            .put("Dodrio", "Dodrio")
            .put("Seel", "Otaria")
            .put("Dewgong", "Lamantine")
            .put("Grimer", "Tadmorv")
            .put("Muk", "Grotadmorv")
            .put("Shellder", "Kokiyas")
            .put("Cloyster", "Crustabri")
            .put("Gastly", "Fantominus")
            .put("Haunter", "Spectrum")
            .put("Gengar", "Ectoplasma")
            .put("Onix", "Onix")
            .put("Drowzee", "Soporifik")
            .put("Hypno", "Hypnomade")
            .put("Krabby", "Krabby")
            .put("Kingler", "Krabboss")
            .put("Voltorb", "Voltorbe")
            .put("Electrode", "Électrode")
            .put("Exeggcute", "Nœunœuf")
            .put("Exeggutor", "Noadkoko")
            .put("Cubone", "Osselait")
            .put("Marowak", "Ossatueur")
            .put("Hitmonlee", "Kicklee")
            .put("Hitmonchan", "Tygnon")
            .put("Lickitung", "Excelangue")
            .put("Koffing", "Smogo")
            .put("Weezing", "Smogogo")
            .put("Rhyhorn", "Rhinocorne")
            .put("Rhydon", "Rhinoféros")
            .put("Chansey", "Leveinard")
            .put("Tangela", "Saquedeneu")
            .put("Kangaskhan", "Kangourex")
            .put("Horsea", "Hypotrempe")
            .put("Seadra", "Hypocéan")
            .put("Goldeen", "Poissirène")
            .put("Seaking", "Poissoroy")
            .put("Staryu", "Stari")
            .put("Starmie", "Staross")
            .put("Mr. Mime", "M. Mime")
            .put("Scyther", "Insécateur")
            .put("Jynx", "Lippoutou")
            .put("Electabuzz", "Élektek")
            .put("Magmar", "Magmar")
            .put("Pinsir", "Scarabrute")
            .put("Tauros", "Tauros")
            .put("Magikarp", "Magicarpe")
            .put("Gyarados", "Léviator")
            .put("Lapras", "Lokhlass")
            .put("Ditto", "Métamorph")
            .put("Eevee", "Évoli")
            .put("Vaporeon", "Aquali")
            .put("Jolteon", "Voltali")
            .put("Flareon", "Pyroli")
            .put("Porygon", "Porygon")
            .put("Omanyte", "Amonita")
            .put("Omastar", "Amonistar")
            .put("Kabuto", "Kabuto")
            .put("Kabutops", "Kabutops")
            .put("Aerodactyl", "Ptéra")
            .put("Snorlax", "Ronflex")
            .put("Articuno", "Artikodin")
            .put("Zapdos", "Électhor")
            .put("Moltres", "Sulfura")
            .put("Dratini", "Minidraco")
            .put("Dragonair", "Draco")
            .put("Dragonite", "Dracolosse")
            .put("Mewtwo", "Mewtwo")
            .put("Mew", "Mew")
            .put("Chikorita", "Germignon")
            .put("Bayleef", "Macronium")
            .put("Meganium", "Méganium")
            .put("Cyndaquil", "Héricendre")
            .put("Quilava", "Feurisson")
            .put("Typhlosion", "Typhlosion")
            .put("Totodile", "Kaiminus")
            .put("Croconaw", "Crocrodil")
            .put("Feraligatr", "Aligatueur")
            .put("Sentret", "Fouinette")
            .put("Furret", "Fouinar")
            .put("Hoothoot", "Hoothoot")
            .put("Noctowl", "Noarfang")
            .put("Ledyba", "Coxy")
            .put("Ledian", "Coxyclaque")
            .put("Spinarak", "Mimigal")
            .put("Ariados", "Migalos")
            .put("Crobat", "Nostenfer")
            .put("Chinchou", "Loupio")
            .put("Lanturn", "Lanturn")
            .put("Pichu", "Pichu")
            .put("Cleffa", "Mélo")
            .put("Igglybuff", "Toudoudou")
            .put("Togepi", "Togepi")
            .put("Togetic", "Togetic")
            .put("Natu", "Natu")
            .put("Xatu", "Xatu")
            .put("Mareep", "Wattouat")
            .put("Flaaffy", "Lainergie")
            .put("Ampharos", "Pharamp")
            .put("Bellossom", "Joliflor")
            .put("Marill", "Marill")
            .put("Azumarill", "Azumarill")
            .put("Sudowoodo", "Simularbre")
            .put("Politoed", "Tarpaud")
            .put("Hoppip", "Granivol")
            .put("Skiploom", "Floravol")
            .put("Jumpluff", "Cotovol")
            .put("Aipom", "Capumain")
            .put("Sunkern", "Tournegrin")
            .put("Sunflora", "Héliatronc")
            .put("Yanma", "Yanma")
            .put("Wooper", "Axoloto")
            .put("Quagsire", "Maraiste")
            .put("Espeon", "Mentali")
            .put("Umbreon", "Noctali")
            .put("Murkrow", "Cornèbre")
            .put("Slowking", "Roigada")
            .put("Misdreavus", "Feuforêve")
            .put("Unown", "Zarbi")
            .put("Wobbuffet", "Qulbutoké")
            .put("Girafarig", "Girafarig")
            .put("Pineco", "Pomdepik")
            .put("Forretress", "Foretress")
            .put("Dunsparce", "Insolourdo")
            .put("Gligar", "Scorplane")
            .put("Steelix", "Steelix")
            .put("Snubbull", "Snubbull")
            .put("Granbull", "Granbull")
            .put("Qwilfish", "Qwilfish")
            .put("Scizor", "Cizayox")
            .put("Shuckle", "Caratroc")
            .put("Heracross", "Scarhino")
            .put("Sneasel", "Farfuret")
            .put("Teddiursa", "Teddiursa")
            .put("Ursaring", "Ursaring")
            .put("Slugma", "Limagma")
            .put("Magcargo", "Volcaropod")
            .put("Swinub", "Marcacrin")
            .put("Piloswine", "Cochignon")
            .put("Corsola", "Corayon")
            .put("Remoraid", "Rémoraid")
            .put("Octillery", "Octillery")
            .put("Delibird", "Cadoizo")
            .put("Mantine", "Démanta")
            .put("Skarmory", "Airmure")
            .put("Houndour", "Malosse")
            .put("Houndoom", "Démolosse")
            .put("Kingdra", "Hyporoi")
            .put("Phanpy", "Phanpy")
            .put("Donphan", "Donphan")
            .put("Porygon2", "Porygon2")
            .put("Stantler", "Cerfrousse")
            .put("Smeargle", "Queulorior")
            .put("Tyrogue", "Debugant")
            .put("Hitmontop", "Kapoera")
            .put("Smoochum", "Lippouti")
            .put("Elekid", "Élekid")
            .put("Magby", "Magby")
            .put("Miltank", "Écrémeuh")
            .put("Blissey", "Leuphorie")
            .put("Raikou", "Raikou")
            .put("Entei", "Entei")
            .put("Suicune", "Suicune")
            .put("Larvitar", "Embrylex")
            .put("Pupitar", "Ymphect")
            .put("Tyranitar", "Tyranocif")
            .put("Lugia", "Lugia")
            .put("Ho-Oh", "Ho-Oh")
            .put("Celebi", "Celebi")
            .put("Treecko", "Arcko")
            .put("Grovyle", "Massko")
            .put("Sceptile", "Jungko")
            .put("Torchic", "Poussifeu")
            .put("Combusken", "Galifeu")
            .put("Blaziken", "Braségali")
            .put("Mudkip", "Gobou")
            .put("Marshtomp", "Flobio")
            .put("Swampert", "Laggron")
            .put("Poochyena", "Medhyèna")
            .put("Mightyena", "Grahyèna")
            .put("Zigzagoon", "Zigzaton")
            .put("Linoone", "Linéon")
            .put("Wurmple", "Chenipotte")
            .put("Silcoon", "Armulys")
            .put("Beautifly", "Charmillon")
            .put("Cascoon", "Blindalys")
            .put("Dustox", "Papinox")
            .put("Lotad", "Nénupiot")
            .put("Lombre", "Lombre")
            .put("Ludicolo", "Ludicolo")
            .put("Seedot", "Grainipiot")
            .put("Nuzleaf", "Pifeuil")
            .put("Shiftry", "Tengalice")
            .put("Taillow", "Nirondelle")
            .put("Swellow", "Hélédelle")
            .put("Wingull", "Goélise")
            .put("Pelipper", "Bekipan")
            .put("Ralts", "Tarsal")
            .put("Kirlia", "Kirlia")
            .put("Gardevoir", "Gardevoir")
            .put("Surskit", "Arakdo")
            .put("Masquerain", "Maskadra")
            .put("Shroomish", "Balignon")
            .put("Breloom", "Chapignon")
            .put("Slakoth", "Parécool")
            .put("Vigoroth", "Vigoroth")
            .put("Slaking", "Monaflèmit")
            .put("Nincada", "Ningale")
            .put("Ninjask", "Ninjask")
            .put("Shedinja", "Munja")
            .put("Whismur", "Chuchmur")
            .put("Loudred", "Ramboum")
            .put("Exploud", "Brouhabam")
            .put("Makuhita", "Makuhita")
            .put("Hariyama", "Hariyama")
            .put("Azurill", "Azurill")
            .put("Nosepass", "Tarinor")
            .put("Skitty", "Skitty")
            .put("Delcatty", "Delcatty")
            .put("Sableye", "Ténéfix")
            .put("Mawile", "Mysdibule")
            .put("Aron", "Galekid")
            .put("Lairon", "Galegon")
            .put("Aggron", "Galeking")
            .put("Meditite", "Méditikka")
            .put("Medicham", "Charmina")
            .put("Electrike", "Dynavolt")
            .put("Manectric", "Élecsprint")
            .put("Plusle", "Posipi")
            .put("Minun", "Négapi")
            .put("Volbeat", "Muciole")
            .put("Illumise", "Lumivole")
            .put("Roselia", "Rosélia")
            .put("Gulpin", "Gloupti")
            .put("Swalot", "Avaltout")
            .put("Carvanha", "Carvanha")
            .put("Sharpedo", "Sharpedo")
            .put("Wailmer", "Wailmer")
            .put("Wailord", "Wailord")
            .put("Numel", "Chamallot")
            .put("Camerupt", "Camérupt")
            .put("Torkoal", "Chartor")
            .put("Spoink", "Spoink")
            .put("Grumpig", "Groret")
            .put("Spinda", "Spinda")
            .put("Trapinch", "Kraknoix")
            .put("Vibrava", "Vibraninf")
            .put("Flygon", "Libégon")
            .put("Cacnea", "Cacnea")
            .put("Cacturne", "Cacturne")
            .put("Swablu", "Tylton")
            .put("Altaria", "Altaria")
            .put("Zangoose", "Mangriff")
            .put("Seviper", "Séviper")
            .put("Lunatone", "Séléroc")
            .put("Solrock", "Solaroc")
            .put("Barboach", "Barloche")
            .put("Whiscash", "Barbicha")
            .put("Corphish", "Écrapince")
            .put("Crawdaunt", "Colhomard")
            .put("Baltoy", "Balbuto")
            .put("Claydol", "Kaorine")
            .put("Lileep", "Lilia")
            .put("Cradily", "Vacilys")
            .put("Anorith", "Anorith")
            .put("Armaldo", "Armaldo")
            .put("Feebas", "Barpau")
            .put("Milotic", "Milobellus")
            .put("Castform", "Morphéo")
            .put("Kecleon", "Kecleon")
            .put("Shuppet", "Polichombr")
            .put("Banette", "Branette")
            .put("Duskull", "Skelénox")
            .put("Dusclops", "Téraclope")
            .put("Tropius", "Tropius")
            .put("Chimecho", "Éoko")
            .put("Absol", "Absol")
            .put("Wynaut", "Okéoké")
            .put("Snorunt", "Stalgamin")
            .put("Glalie", "Oniglali")
            .put("Spheal", "Obalie")
            .put("Sealeo", "Phogleur")
            .put("Walrein", "Kaimorse")
            .put("Clamperl", "Coquiperl")
            .put("Huntail", "Serpang")
            .put("Gorebyss", "Rosabyss")
            .put("Relicanth", "Relicanth")
            .put("Luvdisc", "Lovdisc")
            .put("Bagon", "Draby")
            .put("Shelgon", "Drackhaus")
            .put("Salamence", "Drattak")
            .put("Beldum", "Terhal")
            .put("Metang", "Métang")
            .put("Metagross", "Métalosse")
            .put("Regirock", "Regirock")
            .put("Regice", "Regice")
            .put("Registeel", "Registeel")
            .put("Latias", "Latias")
            .put("Latios", "Latios")
            .put("Kyogre", "Kyogre")
            .put("Groudon", "Groudon")
            .put("Rayquaza", "Rayquaza")
            .put("Jirachi", "Jirachi")
            .put("Deoxys", "Deoxys")
            .build();

    public static ImmutableMap<String, String> POKEMONS_TO_JAPANESE = ImmutableMap.<String, String>builder()
            .put("Bulbasaur", "フシギダネ")
            .put("Ivysaur", "フシギソウ")
            .put("Venusaur", "フシギバナ")
            .put("Charmander", "ヒトカゲ")
            .put("Charmeleon", "リザード")
            .put("Charizard", "リザードン")
            .put("Squirtle", "ゼニガメ")
            .put("Wartortle", "カメール")
            .put("Blastoise", "カメックス")
            .put("Caterpie", "キャタピー")
            .put("Metapod", "トランセル")
            .put("Butterfree", "バタフリー")
            .put("Weedle", "ビードル")
            .put("Kakuna", "コクーン")
            .put("Beedrill", "スピアー")
            .put("Pidgey", "ポッポ")
            .put("Pidgeotto", "ピジョン")
            .put("Pidgeot", "ピジョット")
            .put("Rattata", "コラッタ")
            .put("Raticate", "ラッタ")
            .put("Spearow", "オニスズメ")
            .put("Fearow", "オニドリル")
            .put("Ekans", "アーボ")
            .put("Arbok", "アーボック")
            .put("Pikachu", "ピカチュウ")
            .put("Raichu", "ライチュウ")
            .put("Sandshrew", "サンド")
            .put("Sandslash", "サンドパン")
            .put("Nidoran♀", "ニドラン♀")
            .put("Nidorina", "ニドリーナ")
            .put("Nidoqueen", "ニドクイン")
            .put("Nidoran♂", "ニドラン♂")
            .put("Nidorino", "ニドリーノ")
            .put("Nidoking", "ニドキング")
            .put("Clefairy", "ピッピ")
            .put("Clefable", "ピクシー")
            .put("Vulpix", "ロコン")
            .put("Ninetales", "キュウコン")
            .put("Jigglypuff", "プリン")
            .put("Wigglytuff", "プクリン")
            .put("Zubat", "ズバット")
            .put("Golbat", "ゴルバット")
            .put("Oddish", "ナゾノクサ")
            .put("Gloom", "クサイハナ")
            .put("Vileplume", "ラフレシア")
            .put("Paras", "パラス")
            .put("Parasect", "パラセクト")
            .put("Venonat", "コンパン")
            .put("Venomoth", "モルフォン")
            .put("Diglett", "ディグダ")
            .put("Dugtrio", "ダグトリオ")
            .put("Meowth", "ニャース")
            .put("Persian", "ペルシアン")
            .put("Psyduck", "コダック")
            .put("Golduck", "ゴルダック")
            .put("Mankey", "マンキー")
            .put("Primeape", "オコリザル")
            .put("Growlithe", "ガーディ")
            .put("Arcanine", "ウインディ")
            .put("Poliwag", "ニョロモ")
            .put("Poliwhirl", "ニョロゾ")
            .put("Poliwrath", "ニョロボン")
            .put("Abra", "ケーシィ")
            .put("Kadabra", "ユンゲラー")
            .put("Alakazam", "フーディン")
            .put("Machop", "ワンリキー")
            .put("Machoke", "ゴーリキー")
            .put("Machamp", "カイリキー")
            .put("Bellsprout", "マダツボミ")
            .put("Weepinbell", "ウツドン")
            .put("Victreebel", "ウツボット")
            .put("Tentacool", "メノクラゲ")
            .put("Tentacruel", "ドククラゲ")
            .put("Geodude", "イシツブテ")
            .put("Graveler", "ゴローン")
            .put("Golem", "ゴローニャ")
            .put("Ponyta", "ポニータ")
            .put("Rapidash", "ギャロップ")
            .put("Slowpoke", "ヤドン")
            .put("Slowbro", "ヤドラン")
            .put("Magnemite", "コイル")
            .put("Magneton", "レアコイル")
            .put("Farfetch'd", "カモネギ")
            .put("Doduo", "ドードー")
            .put("Dodrio", "ドードリオ")
            .put("Seel", "パウワウ")
            .put("Dewgong", "ジュゴン")
            .put("Grimer", "ベトベター")
            .put("Muk", "ベトベトン")
            .put("Shellder", "シェルダー")
            .put("Cloyster", "パルシェン")
            .put("Gastly", "ゴース")
            .put("Haunter", "ゴースト")
            .put("Gengar", "ゲンガー")
            .put("Onix", "イワーク")
            .put("Drowzee", "スリープ")
            .put("Hypno", "スリーパー")
            .put("Krabby", "クラブ")
            .put("Kingler", "キングラー")
            .put("Voltorb", "ビリリダマ")
            .put("Electrode", "マルマイン")
            .put("Exeggcute", "タマタマ")
            .put("Exeggutor", "ナッシー")
            .put("Cubone", "カラカラ")
            .put("Marowak", "ガラガラ")
            .put("Hitmonlee", "サワムラー")
            .put("Hitmonchan", "エビワラー")
            .put("Lickitung", "ベロリンガ")
            .put("Koffing", "ドガース")
            .put("Weezing", "マタドガス")
            .put("Rhyhorn", "サイホーン")
            .put("Rhydon", "サイドン")
            .put("Chansey", "ラッキー")
            .put("Tangela", "モンジャラ")
            .put("Kangaskhan", "ガルーラ")
            .put("Horsea", "タッツー")
            .put("Seadra", "シードラ")
            .put("Goldeen", "トサキント")
            .put("Seaking", "アズマオウ")
            .put("Staryu", "ヒトデマン")
            .put("Starmie", "スターミー")
            .put("Mr. Mime", "バリヤード")
            .put("Scyther", "ストライク")
            .put("Jynx", "ルージュラ")
            .put("Electabuzz", "エレブー")
            .put("Magmar", "ブーバー")
            .put("Pinsir", "カイロス")
            .put("Tauros", "ケンタロス")
            .put("Magikarp", "コイキング")
            .put("Gyarados", "ギャラドス")
            .put("Lapras", "ラプラス")
            .put("Ditto", "メタモン")
            .put("Eevee", "イーブイ")
            .put("Vaporeon", "シャワーズ")
            .put("Jolteon", "サンダース")
            .put("Flareon", "ブースター")
            .put("Porygon", "ポリゴン")
            .put("Omanyte", "オムナイト")
            .put("Omastar", "オムスター")
            .put("Kabuto", "カブト")
            .put("Kabutops", "カブトプス")
            .put("Aerodactyl", "プテラ")
            .put("Snorlax", "カビゴン")
            .put("Articuno", "フリーザー")
            .put("Zapdos", "サンダー")
            .put("Moltres", "ファイヤー")
            .put("Dratini", "ミニリュウ")
            .put("Dragonair", "ハクリュー")
            .put("Dragonite", "カイリュー")
            .put("Mewtwo", "ミュウツー")
            .put("Mew", "ミュウ")
            .put("Chikorita", "チコリータ")
            .put("Bayleef", "ベイリーフ")
            .put("Meganium", "メガニウム")
            .put("Cyndaquil", "ヒノアラシ")
            .put("Quilava", "マグマラシ")
            .put("Typhlosion", "バクフーン")
            .put("Totodile", "ワニノコ")
            .put("Croconaw", "アリゲイツ")
            .put("Feraligatr", "オーダイル")
            .put("Sentret", "オタチ")
            .put("Furret", "オオタチ")
            .put("Hoothoot", "ホーホー")
            .put("Noctowl", "ヨルノズク")
            .put("Ledyba", "レディバ")
            .put("Ledian", "レディアン")
            .put("Spinarak", "イトマル")
            .put("Ariados", "アリアドス")
            .put("Crobat", "クロバット")
            .put("Chinchou", "チョンチー")
            .put("Lanturn", "ランターン")
            .put("Pichu", "ピチュー")
            .put("Cleffa", "ピィ")
            .put("Igglybuff", "ププリン")
            .put("Togepi", "トゲピー")
            .put("Togetic", "トゲチック")
            .put("Natu", "ネイティ")
            .put("Xatu", "ネイティオ")
            .put("Mareep", "メリープ")
            .put("Flaaffy", "モココ")
            .put("Ampharos", "デンリュウ")
            .put("Bellossom", "キレイハナ")
            .put("Marill", "マリル")
            .put("Azumarill", "マリルリ")
            .put("Sudowoodo", "ウソッキー")
            .put("Politoed", "ニョロトノ")
            .put("Hoppip", "ハネッコ")
            .put("Skiploom", "ポポッコ")
            .put("Jumpluff", "ワタッコ")
            .put("Aipom", "エイパム")
            .put("Sunkern", "ヒマナッツ")
            .put("Sunflora", "キマワリ")
            .put("Yanma", "ヤンヤンマ")
            .put("Wooper", "ウパー")
            .put("Quagsire", "ヌオー")
            .put("Espeon", "エーフィ")
            .put("Umbreon", "ブラッキー")
            .put("Murkrow", "ヤミカラス")
            .put("Slowking", "ヤドキング")
            .put("Misdreavus", "ムウマ")
            .put("Unown", "アンノーン")
            .put("Wobbuffet", "ソーナンス")
            .put("Girafarig", "キリンリキ")
            .put("Pineco", "クヌギダマ")
            .put("Forretress", "フォレトス")
            .put("Dunsparce", "ノコッチ")
            .put("Gligar", "グライガー")
            .put("Steelix", "ハガネール")
            .put("Snubbull", "ブルー")
            .put("Granbull", "グランブル")
            .put("Qwilfish", "ハリーセン")
            .put("Scizor", "ハッサム")
            .put("Shuckle", "ツボツボ")
            .put("Heracross", "ヘラクロス")
            .put("Sneasel", "ニューラ")
            .put("Teddiursa", "ヒメグマ")
            .put("Ursaring", "リングマ")
            .put("Slugma", "マグマッグ")
            .put("Magcargo", "マグカルゴ")
            .put("Swinub", "ウリムー")
            .put("Piloswine", "イノムー")
            .put("Corsola", "サニーゴ")
            .put("Remoraid", "テッポウオ")
            .put("Octillery", "オクタン")
            .put("Delibird", "デリバード")
            .put("Mantine", "マンタイン")
            .put("Skarmory", "エアームド")
            .put("Houndour", "デルビル")
            .put("Houndoom", "ヘルガー")
            .put("Kingdra", "キングドラ")
            .put("Phanpy", "ゴマゾウ")
            .put("Donphan", "ドンファン")
            .put("Porygon2", "ポリゴン２")
            .put("Stantler", "オドシシ")
            .put("Smeargle", "ドーブル")
            .put("Tyrogue", "バルキー")
            .put("Hitmontop", "カポエラー")
            .put("Smoochum", "ムチュール")
            .put("Elekid", "エレキッド")
            .put("Magby", "ブビィ")
            .put("Miltank", "ミルタンク")
            .put("Blissey", "ハピナス")
            .put("Raikou", "ライコウ")
            .put("Entei", "エンテイ")
            .put("Suicune", "スイクン")
            .put("Larvitar", "ヨーギラス")
            .put("Pupitar", "サナギラス")
            .put("Tyranitar", "バンギラス")
            .put("Lugia", "ルギア")
            .put("Ho-Oh", "ホウオウ")
            .put("Celebi", "セレビィ")
            .put("Treecko", "キモリ")
            .put("Grovyle", "ジュプトル")
            .put("Sceptile", "ジュカイン")
            .put("Torchic", "アチャモ")
            .put("Combusken", "ワカシャモ")
            .put("Blaziken", "バシャーモ")
            .put("Mudkip", "ミズゴロウ")
            .put("Marshtomp", "ヌマクロー")
            .put("Swampert", "ラグラージ")
            .put("Poochyena", "ポチエナ")
            .put("Mightyena", "グラエナ")
            .put("Zigzagoon", "ジグザグマ")
            .put("Linoone", "マッスグマ")
            .put("Wurmple", "ケムッソ")
            .put("Silcoon", "カラサリス")
            .put("Beautifly", "アゲハント")
            .put("Cascoon", "マユルド")
            .put("Dustox", "ドクケイル")
            .put("Lotad", "ハスボー")
            .put("Lombre", "ハスブレロ")
            .put("Ludicolo", "ルンパッパ")
            .put("Seedot", "タネボー")
            .put("Nuzleaf", "コノハナ")
            .put("Shiftry", "ダーテング")
            .put("Taillow", "スバメ")
            .put("Swellow", "オオスバメ")
            .put("Wingull", "キャモメ")
            .put("Pelipper", "ペリッパー")
            .put("Ralts", "ラルトス")
            .put("Kirlia", "キルリア")
            .put("Gardevoir", "サーナイト")
            .put("Surskit", "アメタマ")
            .put("Masquerain", "アメモース")
            .put("Shroomish", "キノココ")
            .put("Breloom", "キノガッサ")
            .put("Slakoth", "ナマケロ")
            .put("Vigoroth", "ヤルキモノ")
            .put("Slaking", "ケッキング")
            .put("Nincada", "ツチニン")
            .put("Ninjask", "テッカニン")
            .put("Shedinja", "ヌケニン")
            .put("Whismur", "ゴニョニョ")
            .put("Loudred", "ドゴーム")
            .put("Exploud", "バクオング")
            .put("Makuhita", "マクノシタ")
            .put("Hariyama", "ハリテヤマ")
            .put("Azurill", "ルリリ")
            .put("Nosepass", "ノズパス")
            .put("Skitty", "エネコ")
            .put("Delcatty", "エネコロロ")
            .put("Sableye", "ヤミラミ")
            .put("Mawile", "クチート")
            .put("Aron", "ココドラ")
            .put("Lairon", "コドラ")
            .put("Aggron", "ボスゴドラ")
            .put("Meditite", "アサナン")
            .put("Medicham", "チャーレム")
            .put("Electrike", "ラクライ")
            .put("Manectric", "ライボルト")
            .put("Plusle", "プラスル")
            .put("Minun", "マイナン")
            .put("Volbeat", "バルビート")
            .put("Illumise", "イルミーゼ")
            .put("Roselia", "ロゼリア")
            .put("Gulpin", "ゴクリン")
            .put("Swalot", "マルノーム")
            .put("Carvanha", "キバニア")
            .put("Sharpedo", "サメハダー")
            .put("Wailmer", "ホエルコ")
            .put("Wailord", "ホエルオー")
            .put("Numel", "ドンメル")
            .put("Camerupt", "バクーダ")
            .put("Torkoal", "コータス")
            .put("Spoink", "バネブー")
            .put("Grumpig", "ブーピッグ")
            .put("Spinda", "パッチール")
            .put("Trapinch", "ナックラー")
            .put("Vibrava", "ビブラーバ")
            .put("Flygon", "フライゴン")
            .put("Cacnea", "サボネア")
            .put("Cacturne", "ノクタス")
            .put("Swablu", "チルット")
            .put("Altaria", "チルタリス")
            .put("Zangoose", "ザングース")
            .put("Seviper", "ハブネーク")
            .put("Lunatone", "ルナトーン")
            .put("Solrock", "ソルロック")
            .put("Barboach", "ドジョッチ")
            .put("Whiscash", "ナマズン")
            .put("Corphish", "ヘイガニ")
            .put("Crawdaunt", "シザリガー")
            .put("Baltoy", "ヤジロン")
            .put("Claydol", "ネンドール")
            .put("Lileep", "リリーラ")
            .put("Cradily", "ユレイドル")
            .put("Anorith", "アノプス")
            .put("Armaldo", "アーマルド")
            .put("Feebas", "ヒンバス")
            .put("Milotic", "ミロカロス")
            .put("Castform", "ポワルン")
            .put("Kecleon", "カクレオン")
            .put("Shuppet", "カゲボウズ")
            .put("Banette", "ジュペッタ")
            .put("Duskull", "ヨマワル")
            .put("Dusclops", "サマヨール")
            .put("Tropius", "トロピウス")
            .put("Chimecho", "チリーン")
            .put("Absol", "アブソル")
            .put("Wynaut", "ソーナノ")
            .put("Snorunt", "ユキワラシ")
            .put("Glalie", "オニゴーリ")
            .put("Spheal", "タマザラシ")
            .put("Sealeo", "トドグラー")
            .put("Walrein", "トドゼルガ")
            .put("Clamperl", "パールル")
            .put("Huntail", "ハンテール")
            .put("Gorebyss", "サクラビス")
            .put("Relicanth", "ジーランス")
            .put("Luvdisc", "ラブカス")
            .put("Bagon", "タツベイ")
            .put("Shelgon", "コモルー")
            .put("Salamence", "ボーマンダ")
            .put("Beldum", "ダンバル")
            .put("Metang", "メタング")
            .put("Metagross", "メタグロス")
            .put("Regirock", "レジロック")
            .put("Regice", "レジアイス")
            .put("Registeel", "レジスチル")
            .put("Latias", "ラティアス")
            .put("Latios", "ラティオス")
            .put("Kyogre", "カイオーガ")
            .put("Groudon", "グラードン")
            .put("Rayquaza", "レックウザ")
            .put("Jirachi", "ジラーチ")
            .put("Deoxys", "デオキシス")
            .build();

    public static ImmutableBiMap<Integer, String> POKEMONS = ImmutableBiMap.<Integer, String>builder()
            .put(1, "Bulbasaur")
            .put(2, "Ivysaur")
            .put(3, "Venusaur")
            .put(4, "Charmander")
            .put(5, "Charmeleon")
            .put(6, "Charizard")
            .put(7, "Squirtle")
            .put(8, "Wartortle")
            .put(9, "Blastoise")
            .put(10, "Caterpie")
            .put(11, "Metapod")
            .put(12, "Butterfree")
            .put(13, "Weedle")
            .put(14, "Kakuna")
            .put(15, "Beedrill")
            .put(16, "Pidgey")
            .put(17, "Pidgeotto")
            .put(18, "Pidgeot")
            .put(19, "Rattata")
            .put(20, "Raticate")
            .put(21, "Spearow")
            .put(22, "Fearow")
            .put(23, "Ekans")
            .put(24, "Arbok")
            .put(25, "Pikachu")
            .put(26, "Raichu")
            .put(27, "Sandshrew")
            .put(28, "Sandslash")
            .put(29, "Nidoran♀")
            .put(30, "Nidorina")
            .put(31, "Nidoqueen")
            .put(32, "Nidoran♂")
            .put(33, "Nidorino")
            .put(34, "Nidoking")
            .put(35, "Clefairy")
            .put(36, "Clefable")
            .put(37, "Vulpix")
            .put(38, "Ninetales")
            .put(39, "Jigglypuff")
            .put(40, "Wigglytuff")
            .put(41, "Zubat")
            .put(42, "Golbat")
            .put(43, "Oddish")
            .put(44, "Gloom")
            .put(45, "Vileplume")
            .put(46, "Paras")
            .put(47, "Parasect")
            .put(48, "Venonat")
            .put(49, "Venomoth")
            .put(50, "Diglett")
            .put(51, "Dugtrio")
            .put(52, "Meowth")
            .put(53, "Persian")
            .put(54, "Psyduck")
            .put(55, "Golduck")
            .put(56, "Mankey")
            .put(57, "Primeape")
            .put(58, "Growlithe")
            .put(59, "Arcanine")
            .put(60, "Poliwag")
            .put(61, "Poliwhirl")
            .put(62, "Poliwrath")
            .put(63, "Abra")
            .put(64, "Kadabra")
            .put(65, "Alakazam")
            .put(66, "Machop")
            .put(67, "Machoke")
            .put(68, "Machamp")
            .put(69, "Bellsprout")
            .put(70, "Weepinbell")
            .put(71, "Victreebel")
            .put(72, "Tentacool")
            .put(73, "Tentacruel")
            .put(74, "Geodude")
            .put(75, "Graveler")
            .put(76, "Golem")
            .put(77, "Ponyta")
            .put(78, "Rapidash")
            .put(79, "Slowpoke")
            .put(80, "Slowbro")
            .put(81, "Magnemite")
            .put(82, "Magneton")
            .put(83, "Farfetch'd")
            .put(84, "Doduo")
            .put(85, "Dodrio")
            .put(86, "Seel")
            .put(87, "Dewgong")
            .put(88, "Grimer")
            .put(89, "Muk")
            .put(90, "Shellder")
            .put(91, "Cloyster")
            .put(92, "Gastly")
            .put(93, "Haunter")
            .put(94, "Gengar")
            .put(95, "Onix")
            .put(96, "Drowzee")
            .put(97, "Hypno")
            .put(98, "Krabby")
            .put(99, "Kingler")
            .put(100, "Voltorb")
            .put(101, "Electrode")
            .put(102, "Exeggcute")
            .put(103, "Exeggutor")
            .put(104, "Cubone")
            .put(105, "Marowak")
            .put(106, "Hitmonlee")
            .put(107, "Hitmonchan")
            .put(108, "Lickitung")
            .put(109, "Koffing")
            .put(110, "Weezing")
            .put(111, "Rhyhorn")
            .put(112, "Rhydon")
            .put(113, "Chansey")
            .put(114, "Tangela")
            .put(115, "Kangaskhan")
            .put(116, "Horsea")
            .put(117, "Seadra")
            .put(118, "Goldeen")
            .put(119, "Seaking")
            .put(120, "Staryu")
            .put(121, "Starmie")
            .put(122, "Mr. Mime")
            .put(123, "Scyther")
            .put(124, "Jynx")
            .put(125, "Electabuzz")
            .put(126, "Magmar")
            .put(127, "Pinsir")
            .put(128, "Tauros")
            .put(129, "Magikarp")
            .put(130, "Gyarados")
            .put(131, "Lapras")
            .put(132, "Ditto")
            .put(133, "Eevee")
            .put(134, "Vaporeon")
            .put(135, "Jolteon")
            .put(136, "Flareon")
            .put(137, "Porygon")
            .put(138, "Omanyte")
            .put(139, "Omastar")
            .put(140, "Kabuto")
            .put(141, "Kabutops")
            .put(142, "Aerodactyl")
            .put(143, "Snorlax")
            .put(144, "Articuno")
            .put(145, "Zapdos")
            .put(146, "Moltres")
            .put(147, "Dratini")
            .put(148, "Dragonair")
            .put(149, "Dragonite")
            .put(150, "Mewtwo")
            .put(151, "Mew")
            .put(152, "Chikorita")
            .put(153, "Bayleef")
            .put(154, "Meganium")
            .put(155, "Cyndaquil")
            .put(156, "Quilava")
            .put(157, "Typhlosion")
            .put(158, "Totodile")
            .put(159, "Croconaw")
            .put(160, "Feraligatr")
            .put(161, "Sentret")
            .put(162, "Furret")
            .put(163, "Hoothoot")
            .put(164, "Noctowl")
            .put(165, "Ledyba")
            .put(166, "Ledian")
            .put(167, "Spinarak")
            .put(168, "Ariados")
            .put(169, "Crobat")
            .put(170, "Chinchou")
            .put(171, "Lanturn")
            .put(172, "Pichu")
            .put(173, "Cleffa")
            .put(174, "Igglybuff")
            .put(175, "Togepi")
            .put(176, "Togetic")
            .put(177, "Natu")
            .put(178, "Xatu")
            .put(179, "Mareep")
            .put(180, "Flaaffy")
            .put(181, "Ampharos")
            .put(182, "Bellossom")
            .put(183, "Marill")
            .put(184, "Azumarill")
            .put(185, "Sudowoodo")
            .put(186, "Politoed")
            .put(187, "Hoppip")
            .put(188, "Skiploom")
            .put(189, "Jumpluff")
            .put(190, "Aipom")
            .put(191, "Sunkern")
            .put(192, "Sunflora")
            .put(193, "Yanma")
            .put(194, "Wooper")
            .put(195, "Quagsire")
            .put(196, "Espeon")
            .put(197, "Umbreon")
            .put(198, "Murkrow")
            .put(199, "Slowking")
            .put(200, "Misdreavus")
            .put(201, "Unown")
            .put(202, "Wobbuffet")
            .put(203, "Girafarig")
            .put(204, "Pineco")
            .put(205, "Forretress")
            .put(206, "Dunsparce")
            .put(207, "Gligar")
            .put(208, "Steelix")
            .put(209, "Snubbull")
            .put(210, "Granbull")
            .put(211, "Qwilfish")
            .put(212, "Scizor")
            .put(213, "Shuckle")
            .put(214, "Heracross")
            .put(215, "Sneasel")
            .put(216, "Teddiursa")
            .put(217, "Ursaring")
            .put(218, "Slugma")
            .put(219, "Magcargo")
            .put(220, "Swinub")
            .put(221, "Piloswine")
            .put(222, "Corsola")
            .put(223, "Remoraid")
            .put(224, "Octillery")
            .put(225, "Delibird")
            .put(226, "Mantine")
            .put(227, "Skarmory")
            .put(228, "Houndour")
            .put(229, "Houndoom")
            .put(230, "Kingdra")
            .put(231, "Phanpy")
            .put(232, "Donphan")
            .put(233, "Porygon2")
            .put(234, "Stantler")
            .put(235, "Smeargle")
            .put(236, "Tyrogue")
            .put(237, "Hitmontop")
            .put(238, "Smoochum")
            .put(239, "Elekid")
            .put(240, "Magby")
            .put(241, "Miltank")
            .put(242, "Blissey")
            .put(243, "Raikou")
            .put(244, "Entei")
            .put(245, "Suicune")
            .put(246, "Larvitar")
            .put(247, "Pupitar")
            .put(248, "Tyranitar")
            .put(249, "Lugia")
            .put(250, "Ho-Oh")
            .put(251, "Celebi")
            .put(252, "Treecko")
            .put(253, "Grovyle")
            .put(254, "Sceptile")
            .put(255, "Torchic")
            .put(256, "Combusken")
            .put(257, "Blaziken")
            .put(258, "Mudkip")
            .put(259, "Marshtomp")
            .put(260, "Swampert")
            .put(261, "Poochyena")
            .put(262, "Mightyena")
            .put(263, "Zigzagoon")
            .put(264, "Linoone")
            .put(265, "Wurmple")
            .put(266, "Silcoon")
            .put(267, "Beautifly")
            .put(268, "Cascoon")
            .put(269, "Dustox")
            .put(270, "Lotad")
            .put(271, "Lombre")
            .put(272, "Ludicolo")
            .put(273, "Seedot")
            .put(274, "Nuzleaf")
            .put(275, "Shiftry")
            .put(276, "Taillow")
            .put(277, "Swellow")
            .put(278, "Wingull")
            .put(279, "Pelipper")
            .put(280, "Ralts")
            .put(281, "Kirlia")
            .put(282, "Gardevoir")
            .put(283, "Surskit")
            .put(284, "Masquerain")
            .put(285, "Shroomish")
            .put(286, "Breloom")
            .put(287, "Slakoth")
            .put(288, "Vigoroth")
            .put(289, "Slaking")
            .put(290, "Nincada")
            .put(291, "Ninjask")
            .put(292, "Shedinja")
            .put(293, "Whismur")
            .put(294, "Loudred")
            .put(295, "Exploud")
            .put(296, "Makuhita")
            .put(297, "Hariyama")
            .put(298, "Azurill")
            .put(299, "Nosepass")
            .put(300, "Skitty")
            .put(301, "Delcatty")
            .put(302, "Sableye")
            .put(303, "Mawile")
            .put(304, "Aron")
            .put(305, "Lairon")
            .put(306, "Aggron")
            .put(307, "Meditite")
            .put(308, "Medicham")
            .put(309, "Electrike")
            .put(310, "Manectric")
            .put(311, "Plusle")
            .put(312, "Minun")
            .put(313, "Volbeat")
            .put(314, "Illumise")
            .put(315, "Roselia")
            .put(316, "Gulpin")
            .put(317, "Swalot")
            .put(318, "Carvanha")
            .put(319, "Sharpedo")
            .put(320, "Wailmer")
            .put(321, "Wailord")
            .put(322, "Numel")
            .put(323, "Camerupt")
            .put(324, "Torkoal")
            .put(325, "Spoink")
            .put(326, "Grumpig")
            .put(327, "Spinda")
            .put(328, "Trapinch")
            .put(329, "Vibrava")
            .put(330, "Flygon")
            .put(331, "Cacnea")
            .put(332, "Cacturne")
            .put(333, "Swablu")
            .put(334, "Altaria")
            .put(335, "Zangoose")
            .put(336, "Seviper")
            .put(337, "Lunatone")
            .put(338, "Solrock")
            .put(339, "Barboach")
            .put(340, "Whiscash")
            .put(341, "Corphish")
            .put(342, "Crawdaunt")
            .put(343, "Baltoy")
            .put(344, "Claydol")
            .put(345, "Lileep")
            .put(346, "Cradily")
            .put(347, "Anorith")
            .put(348, "Armaldo")
            .put(349, "Feebas")
            .put(350, "Milotic")
            .put(351, "Castform")
            .put(352, "Kecleon")
            .put(353, "Shuppet")
            .put(354, "Banette")
            .put(355, "Duskull")
            .put(356, "Dusclops")
            .put(357, "Tropius")
            .put(358, "Chimecho")
            .put(359, "Absol")
            .put(360, "Wynaut")
            .put(361, "Snorunt")
            .put(362, "Glalie")
            .put(363, "Spheal")
            .put(364, "Sealeo")
            .put(365, "Walrein")
            .put(366, "Clamperl")
            .put(367, "Huntail")
            .put(368, "Gorebyss")
            .put(369, "Relicanth")
            .put(370, "Luvdisc")
            .put(371, "Bagon")
            .put(372, "Shelgon")
            .put(373, "Salamence")
            .put(374, "Beldum")
            .put(375, "Metang")
            .put(376, "Metagross")
            .put(377, "Regirock")
            .put(378, "Regice")
            .put(379, "Registeel")
            .put(380, "Latias")
            .put(381, "Latios")
            .put(382, "Kyogre")
            .put(383, "Groudon")
            .put(384, "Rayquaza")
            .put(385, "Jirachi")
            .put(386, "Deoxys")
            .build();

    public static final Map<String, String> FRENCH_POKEMON_NAMES = ImmutableMap.<String, String>builder()
            .put("Grass Energy", "Énergie Plante")
            .put("Lightning Energy", "Énergie Electrique")
            .put("Water Energy", "Énergie Eau")
            .put("Psychic Energy", "Énergie Psy")
            .put("Fire Energy", "Énergie Feu")
            .put("Metal Energy", "Énergie Métal")
            .put("Fighting Energy", "Énergie Combat")
            .put("Darkness Energy", "Énergie Obscurité")
            .put("No.1 Trainer", "Entraineur No.1")
            .put("No.2 Trainer", "Entraineur No.2")
            .put("No.3 Trainer", "Entraineur No.3")
            .put("", "")
            .build();

    public static final Pattern TRAINERS = Pattern.compile("(Blaine|Giovanni|Koga|Rocket|Sabrina|Erika|_____|Lt. Surge|Misty|Brock|Team Aqua|Team Magma|Falkner|Bugsy|Whitney|Morty|Jasmine|Chuck|Pryce|Clair|Janine|Will|Bruno|Karen|Lance)'s (.*)");
    public static final Pattern ZARBI = Pattern.compile("Unown (.)");
    public static final Pattern DARK = Pattern.compile("Dark (.*)");
    public static final Pattern LIGHT = Pattern.compile("Light (.*)");
    public static final Pattern SHINING = Pattern.compile("Shining (.*)");
    public static final Pattern EX = Pattern.compile("(.*) ex");
    public static final Pattern DELTA = Pattern.compile("(.*) δ");

    public static final Map<Pattern, String> FRENCH_PATTERNS = ImmutableMap.of(
        DARK, "%s obscur",
        LIGHT, "%s lumineux",
        SHINING, "%s brillant",
        DELTA, "%s δ",
        EX, "%s ex");

    public static final Map<Pattern, String> JAPANESE_PATTERNS = ImmutableMap.of(
        DARK, "わるい%s",
        LIGHT, "やさしい%s",
        SHINING, "ひかる%s",
        DELTA, "%s δ",
        EX, "%s ex");

    public static final Map<String, String> TRAINERS_MAPPING = ImmutableMap.<String, String>builder()
            .put("Blaine", "Auguste")
            .put("Giovanni", "Giovanni")
            .put("Koga", "Koga")
            .put("Rocket", "Rocket")
            .put("Sabrina", "Sabrina")
            .put("Erika", "Erika")
            .put("Brock", "Pierre")
            .put("Misty", "Ondine")
            .put("Lt. Surge", "Major Bob")
            .put("Team Aqua", "Team Aqua")
            .put("Team Magma", "Team Magma")
            .put("Falkner", "Albert")
            .put("Bugsy", "Hector")
            .put("Whitney", "Blance")
            .put("Morty", "Mortimer")
            .put("Jasmine", "Jasmine")
            .put("Chuck", "Chuck")
            .put("Pryce", "Frédo")
            .put("Clair", "Jasmine")
            .put("Janine", "Jeannine")
            .put("Will", "Clément")
            .put("Bruno", "Aldo")
            .put("Karen", "Marion")
            .put("Lance", "Peter")
            .put("_____", "_____")
            .build();

    public static final Map<String, String> TRAINERS_MAPPING_PRONOUN = ImmutableMap.<String, String>builder()
            .put("Blaine", "de")
            .put("Giovanni", "de ")
            .put("Koga", "de ")
            .put("Rocket", "des ")
            .put("Sabrina", "de ")
            .put("Erika", "d'")
            .put("_____", "de ")
            .put("Brock", "de ")
            .put("Misty", "de ")
            .put("Lt. Surge", "du ")
            .put("Team Aqua", "de la ")
            .put("Team Magma", "de la ")
            .put("Falkner", "d'")
            .put("Bugsy", "d'")
            .put("Whitney", "de ")
            .put("Morty", "de ")
            .put("Jasmine", "de ")
            .put("Chuck", "de ")
            .put("Pryce", "de ")
            .put("Clair", "de ")
            .put("Janine", "de ")
            .put("Will", "de ")
            .put("Bruno", "d'")
            .put("Karen", "de ")
            .put("Lance", "de ")
            .build();

    public static final Map<String, String> FRENCH_NAMES = ImmutableMap.<String, String>builder()
            .put("Awakening Legends", "L'éveil des légendes")
            .put("Base Expansion Pack", "Set de base")
            .put("Bulbasaur Deck", "Deck Bulbizarre")
            .put("Challenge from the Darkness", "Challenge de l'obscurité")
            .put("Championship", "Championnats")
            .put("Chikorita Half Deck", "Demi-deck Germignon")
            .put("CoroCoro Best Photo Contest", "Concours photo CoroCoro")
            .put("Crossing the Ruins...", "Traverser les ruines…")
            .put("Darkness, and to Light...", "Ténèbres, vers la lumière…")
            .put("Evolution Communication Campaign", "Campagne d'évolution")
            .put("Expansion Pack", "Pack expension")
            .put("Gold, Silver, to a New World...", "Or, Argent, vers un nouveau monde…")
            .put("Green Deck", "Deck vert")
            .put("Guren Town Gym", "Arène de Cramois'Île")
            .put("Hanada City Gym", "Arène d'Azuria")
            .put("How I Became a Pokémon Card", "Comment je suis devenu une carte Pokémon")
            .put("J Promotional cards", "Promo J")
            .put("Kuchiba City Gym", "Arène de Carmin sur Mer")
            .put("McDonald's Original Minimum Pack", "Pack McDonald's")
            .put("Mysterious Mountains", "Montagnes mysterieuses")
            .put("Mystery of the Fossils", "Le mystère des fossiles")
            .put("Nivi City Gym", "Arène d'Argenta")
            .put("P Promotional cards", "Promo P")
            .put("Pokemon Fan Club", "Fan club Pokémon")
            .put("Pokémon Jungle", "Jungle")
            .put("Pokémon Song Best Collection", "Meilleures chansons Pokémon")
            .put("Pokémon-e Starter Deck", "Deck e-starter")
            .put("Rainbow Island", "Île arc-en-ciel")
            .put("Red Deck", "Deck rouge")
            .put("Rocket Gang", "Team Rocket")
            .put("Series 1 (Blue)", "Série 1 (Bleu)")
            .put("Series 2 (Red)", "Série 2 (Rouge)")
            .put("Series 3 (Green)", "Série 3 (Vert)")
            .put("Southern Islands", "Îles du sud")
            .put("Split Earth", "Terre divisée")
            .put("Squirtle Deck", "Deck Carapuce")
            .put("T Promotional cards", "Promo T")
            .put("Tamamushi City Gym", "Arène de Céladopole")
            .put("The Town on no Map", "La ville sur aucune carte")
            .put("Theater Limited VS Pack", "Pack VS cinéma")
            .put("Totodile Half Deck", "Demi-deck Kaiminus")
            .put("Tropical Island", "Ile tropicale")
            .put("Tropical Mega Battle Phone Cards", "Cartes téléphoniques Tropical Mega Battle")
            .put("Tyranitar Half Deck", "Demi-deck Tyranocif")
            .put("Wind from the Sea", "Vent de la mer")
            .put("Yamabuki City Gym", "Arène de Safrania")
            .build();


    public static final Map<String, String> JAPANESE_POKEMON_NAMES = ImmutableMap.<String, String>builder()
            .put("", "")
            .build();

    public static final Map<String, String> JAPANESE_TRAINERS_MAPPING = ImmutableMap.<String, String>builder()
            .put("Blaine", "カツラ")
            .put("Giovanni", "サカキ")
            .put("Koga", "キョウ")
            .put("Rocket", "R団")
            .put("Sabrina", "ナツメ")
            .put("Erika", "エリカ")
            .put("Brock", "タケシ")
            .put("Misty", "カスミ")
            .put("Lt. Surge", "マチス")
            .put("_____", "_____")
            .put("Team Aqua", "アクア団")
            .put("Team Magma", "マグマ団")
            .build();

    public static final Set<Type> NON_POKEMON_TYPES = ImmutableSet.of(
            TRAINER,
            ENERGY,
            DECK_LIST,
            ARTWORK,
            EXTRA_RULE,
            PASS_CARD);

    public static final ImmutableBiMap<String, Integer> REVERSED_POKEMON = POKEMONS.inverse();
}
