package card_reader

val EX_ERA = setOf("ADV Expansion Pack",
    "Magma VS Aqua: Two Ambitions",
    "Miracle of the Desert",
    "Rulers of the Heavens",
    "Undone Seal",
    "ADV-P Promotional cards",
    "PLAY Promotional cards",
    "Treecko Constructed Starter Deck",
    "Torchic Constructed Starter Deck",
    "Mudkip Constructed Starter Deck",
    "Flygon Constructed Starter Deck",
    "Salamence Constructed Starter Deck",
    "Movie Commemoration VS Pack",
    "Magma Half Deck 1",
    "Magma Half Deck 2",
    "Aqua Half Deck 1",
    "Aqua Half Deck 2",
    "Latias Half Deck",
    "Latios Half Deck",
    "Metagross Constructed Starter Deck",
    "Flight of Legends",
    "Clash of the Blue Sky",
    "Rocket Gang Strikes Back",
    "Golden Sky",
    "Silvery Ocean",
    "Mirage Forest",
    "Holon Research Tower",
    "Holon Phantom",
    "Miracle Crystal",
    "Offense and Defense of the Furthest Ends",
    "PCG-P Promotional cards",
    "Venusaur Starter Deck",
    "Charizard Starter Deck",
    "Blastoise Starter Deck",
    "Deoxys Constructed Starter Deck",
    "Rayquaza Constructed Starter Deck",
    "Movie Commemoration VS Pack: Sky-Splitting Deoxys",
    "Black Half Deck 1",
    "Black Half Deck 2",
    "Silver Half Deck 1",
    "Silver Half Deck 2",
    "Deoxys Half Deck",
    "Rayquaza Half Deck",
    "Grass Quick Construction Pack",
    "Fire Quick Construction Pack",
    "Water Quick Construction Pack",
    "Lightning Quick Construction Pack",
    "Psychic Quick Construction Pack",
    "Fighting Quick Construction Pack",
    "Meganium Constructed Starter Deck",
    "Typhlosion Constructed Starter Deck",
    "Feraligatr Constructed Starter Deck",
    "PokéPark Forest",
    "PokéPark Blue",
    "Mirage's Mew Constructed Starter Deck",
    "Bulbasaur Quarter Deck",
    "Torchic Quarter Deck",
    "Master Kit Side Deck",
    "Movie Commemoration VS Pack: Aura's Lucario",
    "Holon Research Tower Fire Quarter Deck",
    "Holon Research Tower Lightning Quarter Deck",
    "Holon Research Tower Water Quarter Deck",
    "Lucario Quarter Deck",
    "Crawdaunt Quarter Deck",
    "Mew Quarter Deck",
    "Mightyena Quarter Deck",
    "Pokémon Star",
    "Earth's Groudon ex Constructed Starter Deck",
    "Ocean's Kyogre ex Constructed Starter Deck",
    "Shockwave! Tyranitar ex Constructed Standard Deck",
    "Imprison! Gardevoir ex Constructed Standard Deck",
    "Movie Commemoration VS Pack: Sea's Manaphy"
)
